### PR TITLE
 Support deferred loads

### PR DESCRIPTION
**Pull request by akx**
Simply: If the `load` prop is a function and not a thennable, call it first to acquire the promise.

This allows lazy-loading of potentially heavy bundles.

```jsx
<Async load={() => import('superheavybundle.js')} />
```

This also sets up Jest + Enzyme to test things.

### CODE REVIEW

**Comment by didierfranc** [comment]
Do you have an example for that need ? it could be great to have it in the readme

**Comment by akx** [comment]
Sure.

For example `import()` returns a promise, but it starts loading that promise as soon as it's invoked, so if you have code like

```jsx
const MyComponent = import('./ReallyHeavyComponent');

/* conditional code ... */ <Async load={MyComponent} />
```
you end up loading the component even if you don't need it after all.

Instead, with this PR you can do

```jsx
const MyComponent = () => import('./ReallyHeavyComponent');
/* conditional code ... */ <Async load={MyComponent} />
```

to defer that load up to the very last moment.

**Comment by akx** [comment]
Readme also updated :)

**Comment by akx** [comment]
Closing since there are things such as https://github.com/jamiebuilds/react-loadable and the built-in `React.lazy()`/suspense system that do the same thing.

**Comment by didierfranc** [comment]
hi @akx I just updated the `README.md` https://github.com/didierfranc/react-code-splitting/blob/master/README.md

**Pull request closed without merging**
